### ISSUE TITLE
process has died

### ISSUE THREAD

**Issue by cmakelabs** [hoangvietdo/dero#1] opened 2024-08-06 19:14 UTC
Thank you for your efforts, I am trying to run the code of this repo, and I have encountered the following error:

```
[scekf_dero_ros2bag_node-1] [INFO] [1722971522.887453850] [incsl_node]: Finished loading!
[scekf_dero_ros2bag_node-1] [INFO] [1722971522.887461880] [incsl_node]: Running 3D Stochastic Cloning EKF Dead Reckoning Radar Odometry (SCEKF-DeRO)...
[scekf_dero_ros2bag_node-1] [INFO] [1722971522.894969287] [rosbag2_storage]: Opened database '/home/humble/carried_1_dero_dataset_ros2/carried_1_dero_dataset_ros2.db3' for READ_ONLY.
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.013095897] [incsl_node]: IMU: Data received!
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.013351530] [incsl_node]: Gathering IMU data for coarse alingment algorithm and initialization...
[scekf_dero_ros2bag_node-1] [WARN] [1722971523.013381271] [incsl_node]: Waiting for radar msg!
[scekf_dero_ros2bag_node-1] [WARN] [1722971523.013833161] [incsl_node]: Waiting for imu msg!
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.018327656] [incsl_node]: Radar: Data received!
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.018408655] [incsl_node]: Radar: Data received but rejected due to initialization process!
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350020398] [incsl_node]: Coarse alignment: using 5000 IMU samples
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350062977] [incsl_node]: Coarse alignment: initial Euler angle [roll, pitch, yaw] is [179.49, 0.54, 0.00] (degree)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350078717] [incsl_node]: Initialization: gravitational constant is 9.81 (m/s^2)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350113029] [incsl_node]: Initialization: initial position [X, Y, Z] is [0.00, 0.00, 0.00] (m)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350124734] [incsl_node]: Initialization: initial Euler angle [X, Y, Z] is [179.49, 0.54, 0.00] (deg)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350133903] [incsl_node]: Initialization: initial velocity [X, Y, Z] is [0.00, 0.00, 0.00] (m/s)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350141928] [incsl_node]: Initialization: initial gyroscope bias [X, Y, Z] is [-0.04, 0.12, -0.58] (degree/s)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350150343] [incsl_node]: Initialization: initial accelerometer bias [X, Y, Z] is [0.00, -0.00, 0.13] (m/s^2)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350158109] [incsl_node]: Initialization: initial radar scale vector [X, Y, Z] is [1.00, 1.00, 1.00]
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350165467] [incsl_node]: Initialization: imu dt is 0.002443 (second)
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.350172494] [incsl_node]: Initialization: radar dt is 0.100145 (second)
[scekf_dero_ros2bag_node-1] [WARN] [1722971523.352316852] [incsl_node]: Radar PointCloud2 has empty frame_id, setting default frame_id: incsl_radar!
[scekf_dero_ros2bag_node-1] [INFO] [1722971523.356234703] [incsl_node]: Radar: Used as a core sensor!
[ERROR] [scekf_dero_ros2bag_node-1]: process has died [pid 23215, exit code -8, cmd '/home/humble/dero_ws/install/dero/lib/dero/scekf_dero_ros2bag_node --ros-args --params-file /tmp/launch_params_exb0g8ha'].

```
Could you please tell what could be the reason behind this issue? Would be grateful to know

**Comment by hoangvietdo** [comment] 2024-08-08 06:24
Hi,

Thank you for your interest in our work.

I've encountered this error a few times in the past, though it has been rare considering the total number of trials I've conducted. For context, my computer is quite powerful.

My initial guess for the cause of this error is a mismatch between the ROS node loop and the processing time inside the ```while``` loop (for rosbag). If you're using a low-spec PC, I recommend increasing the ROS node loop value (i.e., the ```callback_timer_process_``` variable in ```src/cores/run_ros2bag.cpp```).

Hope this helps!

**Comment by hoangvietdo** [comment] 2024-08-09 17:46
Could you tell me which version of ROS 2 you are using to run the code?

**Comment by hoangvietdo** [comment] 2024-08-11 04:36
I've been concerned that our project might not work properly across different ROS 2 versions since I've only thoroughly tested the code on ROS 2 Foxy. The differences between ROS versions are not trivial.

To verify this, I installed a fresh ROS 2 Foxy on a virtual machine, and the code worked perfectly. Therefore, I recommend using ROS 2 Foxy if you want to run the code quickly. For now, upgrading to another ROS 2 version isn't feasible for me.

However, PRs are absolutely welcome if you manage to get the code running on ROS 2 Humble.

**Comment by hoangvietdo** [comment] 2024-08-13 15:49
As mentioned in the README, i’m using Ubuntu 20.04 with ROS 2 Foxy.

**Comment by hoangvietdo** [comment] 2024-08-15 10:00
Glad it’s working! Could you please close the issue?

**Closed as completed** 2024-08-15 13:04 UTC
